//
//

#define HARDWARE_VERSION_MAJOR 0
#define HARDWARE_VERSION_MINOR 1
#define SOFTWARE_VERSION_MAJOR 9
#define SOFTWARE_VERSION_MINOR 9
#define SOFTWARE_VERSION_PATCH 9

#define VERSION_STRING "01999"
